Fixed absolutely bizarre compile error occuring in Visual Studio.
- VoroniDiagramGenerator wouldn't compile due to a template error somewhere in the standard library.
- Error:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\include\utility(604,1): error C2440: '=': cannot convert from '_Other' to '_Ty'
  In ..\..\src\VoronoiDiagramGenerator.cpp