New GCC: Fixed a bunch of loop variable errors I don't really understand.
for example:
error: loop variable ‘string’ creates a copy from type ‘const std::__cxx11::basic_string<char>’ [-Werror=range-loop-construct]

There was a bunch of stuff about some type not being copyable that was
fixable by making the type auto and letting the compiler worry about it. I
don't understand it either, because the error was telling me to do what the
code was already doing.