Accepted spixi's patch for a C++ syntax error related in sound.cpp.
src/sound.cpp: In member function ‘virtual void sound::{anonymous}::BinauralDelaySoundEffectFilter::MixData(float*, int)’:
src/sound.cpp:1232:40: error: expected primary-expression before ‘int’
 1232 |             const int nsamples_delay = int(std::abs<float>(delay_)*SampleRate);

It is expected that there is a change between C++11 and C++17 which
introduced the issue in the first place.